/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as DeepwikiRouteImport } from './routes/deepwiki'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as VibecodeRouteImport } from './routes/vibecode'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as SkillsSkillIdRouteImport } from './routes/skills.$skillId'
import { Route as ApiVibeChatRouteImport } from './routes/api/vibe/chat'
import { Route as ApiVibeErrorsRouteImport } from './routes/api/vibe/errors'
import { Route as ApiVibeModelsRouteImport } from './routes/api/vibe/models'
import { Route as ApiVibeSandboxesSandboxIdRouteImport } from './routes/api/vibe/sandboxes/$sandboxId'
import { Route as ApiVibeSandboxesSandboxIdFilesRouteImport } from './routes/api/vibe/sandboxes/$sandboxId/files'
import { Route as ApiVibeSandboxesSandboxIdCmdsCmdIdRouteImport } from './routes/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
import { Route as ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRouteImport } from './routes/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepwikiRoute = DeepwikiRouteImport.update({
  id: '/deepwiki',
  path: '/deepwiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const VibecodeRoute = VibecodeRouteImport.update({
  id: '/vibecode',
  path: '/vibecode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibeChatRoute = ApiVibeChatRouteImport.update({
  id: '/api/vibe/chat',
  path: '/api/vibe/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibeErrorsRoute = ApiVibeErrorsRouteImport.update({
  id: '/api/vibe/errors',
  path: '/api/vibe/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibeModelsRoute = ApiVibeModelsRouteImport.update({
  id: '/api/vibe/models',
  path: '/api/vibe/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibeSandboxesSandboxIdRoute =
  ApiVibeSandboxesSandboxIdRouteImport.update({
    id: '/api/vibe/sandboxes/$sandboxId',
    path: '/api/vibe/sandboxes/$sandboxId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVibeSandboxesSandboxIdFilesRoute =
  ApiVibeSandboxesSandboxIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ApiVibeSandboxesSandboxIdRoute,
  } as any)
const ApiVibeSandboxesSandboxIdCmdsCmdIdRoute =
  ApiVibeSandboxesSandboxIdCmdsCmdIdRouteImport.update({
    id: '/cmds/$cmdId',
    path: '/cmds/$cmdId',
    getParentRoute: () => ApiVibeSandboxesSandboxIdRoute,
  } as any)
const ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute =
  ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => ApiVibeSandboxesSandboxIdCmdsCmdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/deepwiki': typeof DeepwikiRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/submit': typeof SubmitRoute
  '/vibecode': typeof VibecodeRoute
  '/api/skills': typeof ApiSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/vibe/chat': typeof ApiVibeChatRoute
  '/api/vibe/errors': typeof ApiVibeErrorsRoute
  '/api/vibe/models': typeof ApiVibeModelsRoute
  '/api/vibe/sandboxes/$sandboxId': typeof ApiVibeSandboxesSandboxIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/files': typeof ApiVibeSandboxesSandboxIdFilesRoute
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/deepwiki': typeof DeepwikiRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/submit': typeof SubmitRoute
  '/vibecode': typeof VibecodeRoute
  '/api/skills': typeof ApiSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/vibe/chat': typeof ApiVibeChatRoute
  '/api/vibe/errors': typeof ApiVibeErrorsRoute
  '/api/vibe/models': typeof ApiVibeModelsRoute
  '/api/vibe/sandboxes/$sandboxId': typeof ApiVibeSandboxesSandboxIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/files': typeof ApiVibeSandboxesSandboxIdFilesRoute
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/deepwiki': typeof DeepwikiRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/submit': typeof SubmitRoute
  '/vibecode': typeof VibecodeRoute
  '/api/skills': typeof ApiSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/vibe/chat': typeof ApiVibeChatRoute
  '/api/vibe/errors': typeof ApiVibeErrorsRoute
  '/api/vibe/models': typeof ApiVibeModelsRoute
  '/api/vibe/sandboxes/$sandboxId': typeof ApiVibeSandboxesSandboxIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/files': typeof ApiVibeSandboxesSandboxIdFilesRoute
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren
  '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs': typeof ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/deepwiki'
    | '/explore'
    | '/library'
    | '/submit'
    | '/vibecode'
    | '/api/skills'
    | '/skills/$skillId'
    | '/api/vibe/chat'
    | '/api/vibe/errors'
    | '/api/vibe/models'
    | '/api/vibe/sandboxes/$sandboxId'
    | '/api/vibe/sandboxes/$sandboxId/files'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/deepwiki'
    | '/explore'
    | '/library'
    | '/submit'
    | '/vibecode'
    | '/api/skills'
    | '/skills/$skillId'
    | '/api/vibe/chat'
    | '/api/vibe/errors'
    | '/api/vibe/models'
    | '/api/vibe/sandboxes/$sandboxId'
    | '/api/vibe/sandboxes/$sandboxId/files'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/deepwiki'
    | '/explore'
    | '/library'
    | '/submit'
    | '/vibecode'
    | '/api/skills'
    | '/skills/$skillId'
    | '/api/vibe/chat'
    | '/api/vibe/errors'
    | '/api/vibe/models'
    | '/api/vibe/sandboxes/$sandboxId'
    | '/api/vibe/sandboxes/$sandboxId/files'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
    | '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  DeepwikiRoute: typeof DeepwikiRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  SubmitRoute: typeof SubmitRoute
  VibecodeRoute: typeof VibecodeRoute
  ApiSkillsRoute: typeof ApiSkillsRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  ApiVibeChatRoute: typeof ApiVibeChatRoute
  ApiVibeErrorsRoute: typeof ApiVibeErrorsRoute
  ApiVibeModelsRoute: typeof ApiVibeModelsRoute
  ApiVibeSandboxesSandboxIdRoute: typeof ApiVibeSandboxesSandboxIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deepwiki': {
      id: '/deepwiki'
      path: '/deepwiki'
      fullPath: '/deepwiki'
      preLoaderRoute: typeof DeepwikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibecode': {
      id: '/vibecode'
      path: '/vibecode'
      fullPath: '/vibecode'
      preLoaderRoute: typeof VibecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe/chat': {
      id: '/api/vibe/chat'
      path: '/api/vibe/chat'
      fullPath: '/api/vibe/chat'
      preLoaderRoute: typeof ApiVibeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe/errors': {
      id: '/api/vibe/errors'
      path: '/api/vibe/errors'
      fullPath: '/api/vibe/errors'
      preLoaderRoute: typeof ApiVibeErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe/models': {
      id: '/api/vibe/models'
      path: '/api/vibe/models'
      fullPath: '/api/vibe/models'
      preLoaderRoute: typeof ApiVibeModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe/sandboxes/$sandboxId': {
      id: '/api/vibe/sandboxes/$sandboxId'
      path: '/api/vibe/sandboxes/$sandboxId'
      fullPath: '/api/vibe/sandboxes/$sandboxId'
      preLoaderRoute: typeof ApiVibeSandboxesSandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe/sandboxes/$sandboxId/files': {
      id: '/api/vibe/sandboxes/$sandboxId/files'
      path: '/files'
      fullPath: '/api/vibe/sandboxes/$sandboxId/files'
      preLoaderRoute: typeof ApiVibeSandboxesSandboxIdFilesRouteImport
      parentRoute: typeof ApiVibeSandboxesSandboxIdRoute
    }
    '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId': {
      id: '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
      path: '/cmds/$cmdId'
      fullPath: '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId'
      preLoaderRoute: typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRouteImport
      parentRoute: typeof ApiVibeSandboxesSandboxIdRoute
    }
    '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs': {
      id: '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'
      path: '/logs'
      fullPath: '/api/vibe/sandboxes/$sandboxId/cmds/$cmdId/logs'
      preLoaderRoute: typeof ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRouteImport
      parentRoute: typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRoute
    }
  }
}

interface ApiVibeSandboxesSandboxIdCmdsCmdIdRouteChildren {
  ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute: typeof ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute
}

const ApiVibeSandboxesSandboxIdCmdsCmdIdRouteChildren: ApiVibeSandboxesSandboxIdCmdsCmdIdRouteChildren =
  {
    ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute:
      ApiVibeSandboxesSandboxIdCmdsCmdIdLogsRoute,
  }

const ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren =
  ApiVibeSandboxesSandboxIdCmdsCmdIdRoute._addFileChildren(
    ApiVibeSandboxesSandboxIdCmdsCmdIdRouteChildren,
  )

interface ApiVibeSandboxesSandboxIdRouteChildren {
  ApiVibeSandboxesSandboxIdFilesRoute: typeof ApiVibeSandboxesSandboxIdFilesRoute
  ApiVibeSandboxesSandboxIdCmdsCmdIdRoute: typeof ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren
}

const ApiVibeSandboxesSandboxIdRouteChildren: ApiVibeSandboxesSandboxIdRouteChildren =
  {
    ApiVibeSandboxesSandboxIdFilesRoute: ApiVibeSandboxesSandboxIdFilesRoute,
    ApiVibeSandboxesSandboxIdCmdsCmdIdRoute:
      ApiVibeSandboxesSandboxIdCmdsCmdIdRouteWithChildren,
  }

const ApiVibeSandboxesSandboxIdRouteWithChildren =
  ApiVibeSandboxesSandboxIdRoute._addFileChildren(
    ApiVibeSandboxesSandboxIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  DeepwikiRoute: DeepwikiRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  SubmitRoute: SubmitRoute,
  VibecodeRoute: VibecodeRoute,
  ApiSkillsRoute: ApiSkillsRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  ApiVibeChatRoute: ApiVibeChatRoute,
  ApiVibeErrorsRoute: ApiVibeErrorsRoute,
  ApiVibeModelsRoute: ApiVibeModelsRoute,
  ApiVibeSandboxesSandboxIdRoute: ApiVibeSandboxesSandboxIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
